apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: my-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: manee2k6/jenkins-docker
        ports:
        - containerPort: 8080
   
   

